//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.04 at 12:56:43 PM CDT 
//


package com.challenge.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ability">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="abilityDetail" type="{http://www.challenge.org/pokemonChallenge}abilityDet"/>
 *         &lt;element name="is_hidden" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="slot" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ability", propOrder = {
    "abilityDetail",
    "isHidden",
    "slot"
})
public class Ability {

    @XmlElement(required = true)
    protected AbilityDet abilityDetail;
    @XmlElement(name = "is_hidden")
    protected boolean isHidden;
    protected int slot;

    /**
     * Gets the value of the abilityDetail property.
     * 
     * @return
     *     possible object is
     *     {@link AbilityDet }
     *     
     */
    public AbilityDet getAbilityDetail() {
        return abilityDetail;
    }

    /**
     * Sets the value of the abilityDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbilityDet }
     *     
     */
    public void setAbilityDetail(AbilityDet value) {
        this.abilityDetail = value;
    }

    /**
     * Gets the value of the isHidden property.
     * 
     */
    public boolean isIsHidden() {
        return isHidden;
    }

    /**
     * Sets the value of the isHidden property.
     * 
     */
    public void setIsHidden(boolean value) {
        this.isHidden = value;
    }

    /**
     * Gets the value of the slot property.
     * 
     */
    public int getSlot() {
        return slot;
    }

    /**
     * Sets the value of the slot property.
     * 
     */
    public void setSlot(int value) {
        this.slot = value;
    }

}
