//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.05.04 at 12:56:43 PM CDT 
//


package com.challenge.beans;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.challenge.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.challenge.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetIdRequest }
     * 
     */
    public GetIdRequest createGetIdRequest() {
        return new GetIdRequest();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncountersRequest }
     * 
     */
    public GetLocationAreaEncountersRequest createGetLocationAreaEncountersRequest() {
        return new GetLocationAreaEncountersRequest();
    }

    /**
     * Create an instance of {@link GetHeldItemsRequest }
     * 
     */
    public GetHeldItemsRequest createGetHeldItemsRequest() {
        return new GetHeldItemsRequest();
    }

    /**
     * Create an instance of {@link GetHeldItemsResponse }
     * 
     */
    public GetHeldItemsResponse createGetHeldItemsResponse() {
        return new GetHeldItemsResponse();
    }

    /**
     * Create an instance of {@link HeldItem }
     * 
     */
    public HeldItem createHeldItem() {
        return new HeldItem();
    }

    /**
     * Create an instance of {@link GetNameResponse }
     * 
     */
    public GetNameResponse createGetNameResponse() {
        return new GetNameResponse();
    }

    /**
     * Create an instance of {@link PokemonName }
     * 
     */
    public PokemonName createPokemonName() {
        return new PokemonName();
    }

    /**
     * Create an instance of {@link GetAbilitiesResponse }
     * 
     */
    public GetAbilitiesResponse createGetAbilitiesResponse() {
        return new GetAbilitiesResponse();
    }

    /**
     * Create an instance of {@link Ability }
     * 
     */
    public Ability createAbility() {
        return new Ability();
    }

    /**
     * Create an instance of {@link GetAbilitiesRequest }
     * 
     */
    public GetAbilitiesRequest createGetAbilitiesRequest() {
        return new GetAbilitiesRequest();
    }

    /**
     * Create an instance of {@link GetBaseExperienceResponse }
     * 
     */
    public GetBaseExperienceResponse createGetBaseExperienceResponse() {
        return new GetBaseExperienceResponse();
    }

    /**
     * Create an instance of {@link BaseExp }
     * 
     */
    public BaseExp createBaseExp() {
        return new BaseExp();
    }

    /**
     * Create an instance of {@link GetBaseExperienceRequest }
     * 
     */
    public GetBaseExperienceRequest createGetBaseExperienceRequest() {
        return new GetBaseExperienceRequest();
    }

    /**
     * Create an instance of {@link GetIdResponse }
     * 
     */
    public GetIdResponse createGetIdResponse() {
        return new GetIdResponse();
    }

    /**
     * Create an instance of {@link GetNameRequest }
     * 
     */
    public GetNameRequest createGetNameRequest() {
        return new GetNameRequest();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncountersResponse }
     * 
     */
    public GetLocationAreaEncountersResponse createGetLocationAreaEncountersResponse() {
        return new GetLocationAreaEncountersResponse();
    }

    /**
     * Create an instance of {@link LocationAreaEncounters }
     * 
     */
    public LocationAreaEncounters createLocationAreaEncounters() {
        return new LocationAreaEncounters();
    }

    /**
     * Create an instance of {@link HeldItemVD }
     * 
     */
    public HeldItemVD createHeldItemVD() {
        return new HeldItemVD();
    }

    /**
     * Create an instance of {@link AbilityDet }
     * 
     */
    public AbilityDet createAbilityDet() {
        return new AbilityDet();
    }

    /**
     * Create an instance of {@link HeldItemVersion }
     * 
     */
    public HeldItemVersion createHeldItemVersion() {
        return new HeldItemVersion();
    }

    /**
     * Create an instance of {@link ItemVD }
     * 
     */
    public ItemVD createItemVD() {
        return new ItemVD();
    }

}
